# Turborepo splits workspaces into apps and packages by convention, so we add both here
packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAge: 4320 # 1 day

# Keep these dependency install scripts disabled.
allowBuilds:
  "@swc/core": false
  cbor-extract: false
  esbuild: false
  unrs-resolver: false
