name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    name: Lint, Format, Typecheck & Build
    runs-on: blacksmith-2vcpu-ubuntu-2404
    defaults:
      run:
        working-directory: ./apps/driver-station
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        working-directory: .
        run: pnpm ci

      - name: Lint
        working-directory: .
        run: pnpm run lint:check

      - name: Format
        working-directory: .
        run: pnpm run format:check

      - name: Typecheck
        working-directory: .
        run: pnpm run typecheck

      - name: Build
        working-directory: .
        run: pnpm run build

      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: driver-station/playwright-report/
      #     retention-days: 30
